project_id = "nimxzvhzxsfkfpnbhphm"

[functions.user-invite]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.get-users]
verify_jwt = false

[functions.get-reports]
verify_jwt = false

[functions.get-payments]
verify_jwt = false

[functions.manage-settings]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false