project_id = "nimxzvhzxsfkfpnbhphm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://epacific.lovable.app"
additional_redirect_urls = [
  "https://epacific.lovable.app",
  "https://epacific.lovable.app/set-password",
  "https://epacific.lovable.app/handle-invite"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
enable_signup = false
external_redirect_scheme = "https://login.epacifictechnologies.com/"

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[functions.send-invitation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.setup-demo-accounts]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.bootstrap-demo-admin]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.session-verify]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.get-users]
verify_jwt = false

[functions.get-reports]
verify_jwt = false

[functions.get-payments]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.manageUser]
verify_jwt = false

[functions.user-invite]
verify_jwt = true

[functions.setup-password]
verify_jwt = false

[functions.create-test-notifications]
verify_jwt = false